### PR TITLE
Create ru_RU.lang

### PR DESCRIPTION
**Pull request by Adaptivity**
What is done so far:
1) Translated into Russian
2) Fixed mistakes in README.md and in en_US.lang
3) Move and changed mcmod.info
4) Added pack.mcmeta

Notes:
1) Can you add %s tags to [these lines](https://github.com/TheDrunkMafia/ThaumicInfusion/blob/master/src/main/resources/assets/thaumicinfusion/lang/en_US.lang#L16-L18)? Because I need to swap them with aspect names. [Example of %s tag](https://github.com/BCA-Team/Buildcraft-Additions/blob/2.1.x/src/main/resources/assets/bcadditions/lang/en_US.lang#L55)
2) .lang keys mentioned above seems not used for blocks which can be obtained in creative or in NEI. Can you fix it?
3) Also, [this line](https://github.com/TheDrunkMafia/ThaumicInfusion/blob/ed0399bdb6e03828c7af5c20ec5316e495e43c3a/src/main/java/drunkmafia/thaumicinfusion/common/intergration/ThaumcraftIntergration.java#L113) hardcoded. I mean "Cost" word

### CODE REVIEW

**Comment by TheDrunkMafia** [comment]
I'll merge this in abit, I need to reconfigure my local repository.

**Comment by Adaptivity** [comment]
Are you done with updates from local repository? If so, I can update my PR and you'll be able to pull it automatically

**Comment by TheDrunkMafia** [comment]
Aye, I've updated it all. Your going to have to make it compatible with the changes Ive made.

**Comment by Adaptivity** [comment]
I'll update my PR within an hour.

**Comment by Adaptivity** [comment]
Done.

**Comment by TheDrunkMafia** [comment]
Cheers man, I'll add you to the credits of the mod.

**Comment by Adaptivity** [comment]
Can you look into %s tags? "Cost" word should have it too.

**Pull request merged**
